import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "/pages/api/auth/[...nextauth]";
import { cookies } from "next/headers";
import DarkMode from "./DarkMode";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  let res = cookies().get("mode");

  return (
    <html lang="en">
      <body
        className={res != undefined && res.value == "dark" ? "dark-mode" : null}
      >
        <div className="navbar">
          <Link href="/" className="logo">
            forum
          </Link>
          <Link href="/list">List</Link>
          <LoginBtn session={session} />
          <DarkMode />
        </div>
        {children}
      </body>
    </html>
  );
}
